# Generated by Django 2.0.5 on 2018-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('Name', models.CharField(default='', max_length=100)),
                ('Day', models.IntegerField(choices=[(1, 'SAT'), (2, 'SUN'), (3, 'MON'), (4, 'TUE'), (5, 'WED'), (6, 'SAT-MON'), (7, 'SUN-TUE')], default=0)),
                ('Time', models.IntegerField(choices=[(1, '07:45-09:15'), (2, '09:15-10:45'), (3, '10:45-12:15'), (4, '13:00-15:00'), (5, '15:00-17:00')], default=0)),
                ('Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cName', models.CharField(max_length=100)),
                ('day', models.IntegerField(choices=[(1, 'SAT'), (2, 'SUN'), (3, 'MON'), (4, 'TUE'), (5, 'WED'), (6, 'SAT-MON'), (7, 'SUN-TUE')])),
                ('time', models.IntegerField(choices=[(1, '07:45-09:15'), (2, '09:15-10:45'), (3, '10:45-12:15'), (4, '13:00-15:00'), (5, '15:00-17:00')])),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
